#--------------------------------------------------------------------------------------------------
# Hardware Configuration: mediarr
#--------------------------------------------------------------------------------------------------

# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.

{ inputs, self, ... }: {
  flake.nixosModules.mediarrHardware = { config, lib, pkgs, modulesPath, ... }: {
    imports = [
      (modulesPath + "/profiles/qemu-guest.nix")
    ];

    boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ ];
    boot.extraModulePackages = [ ];

    fileSystems."/" =
      { device = "/dev/disk/by-uuid/f54b381d-5c30-40f3-accb-ff76bd486f89";
        fsType = "ext4";
      };

    swapDevices =
      [ { device = "/dev/disk/by-uuid/3b6abe19-55d4-4f89-9046-b2f1ac3528df"; }
      ];

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  };
}

#---------------------------------------------------------------------------------------------------
# End
#---------------------------------------------------------------------------------------------------
