#--------------------------------------------------------------------------------------------------
# Hardware Configuration: armvm
#--------------------------------------------------------------------------------------------------

# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.

{ inputs, self, ... }: {
  flake.nixosModules.armvm-hw = { config, lib, pkgs, modulesPath, ... }: {

    imports = [ ];

    boot.initrd.availableKernelModules = [ "ehci_pci" "xhci_pci" "usbhid" "sr_mod" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ ];
    boot.extraModulePackages = [ ];

    fileSystems."/" =
      { device = "/dev/disk/by-uuid/b97cba45-f908-4c8a-af01-0ad45a82ea2b";
        fsType = "ext4";
      };

    fileSystems."/boot" =
      { device = "/dev/disk/by-uuid/DA6E-AF66";
        fsType = "vfat";
        options = [ "fmask=0077" "dmask=0077" ];
      };

    swapDevices =
      [ { device = "/dev/disk/by-uuid/b36551a2-c196-42cd-abef-a091a05a286c"; }
      ];

    nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
    hardware.parallels.enable = true;
    nixpkgs.config.allowUnfreePackages = [ "prl-tools" ];

  };
}

#---------------------------------------------------------------------------------------------------
# End
#---------------------------------------------------------------------------------------------------
