#--------------------------------------------------------------------------------------------------
# Hardware Configuration: armvm
#--------------------------------------------------------------------------------------------------

# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.

{ inputs, self, ... }: {
  flake.nixosModules.armvm-hw = { config, lib, pkgs, modulesPath, ... }: {

    imports = [ ];

    boot.initrd.availableKernelModules = [ "ehci_pci" "xhci_pci" "usbhid" "sr_mod" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ ];
    #boot.kernelParams = [ "reboot=acpi" ];
    boot.extraModulePackages = [ ];

    fileSystems."/" =
      { device = "/dev/disk/by-uuid/32b55a51-576c-4382-9635-c48ae6b851f3";
        fsType = "ext4";
      };

    fileSystems."/boot" =
      { device = "/dev/disk/by-uuid/0532-E79D";
        fsType = "vfat";
        options = [ "fmask=0077" "dmask=0077" ];
      };

    swapDevices =
      [ { device = "/dev/disk/by-uuid/a03871b3-60a8-46d5-9031-0a2f143656cb"; }
      ];

    nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
    hardware.parallels.enable = true;
    nixpkgs.config.allowUnfreePackages = [ "prl-tools" ];

  };
}

#---------------------------------------------------------------------------------------------------
# End
#---------------------------------------------------------------------------------------------------
